### ISSUE TITLE
Hyperlinking to a worksheet that has underscores in the name will remove the underscores from the link causing it to not work.

### ISSUE THREAD

**Issue by realtradam** [caxlsx/caxlsx#311] opened 2023-11-10 17:27 UTC
I need to generate a spreadsheet which has several worksheet names that use underscores. It would appear to me that when inputting these names into the hyperlink method(`sheet.add_hyperlink`) it converts it from "snake case" to "camel case" but looking through the code I wasn't able to pinpoint where this was happening. I suspect it may be the "htmlentities" gem that is causing this but some help for investigation would be appreciated.

Here is a simple script which outlines the issue:

```ruby
require 'caxlsx'

output = "test.xlsx"

package = Axlsx::Package.new
workbook = package.workbook

workbook.add_worksheet(name: 'BasicName') do |sheet|
  sheet.add_row ["basic_name_with_underscore"]
  sheet.add_hyperlink(
    location: "'basic_name_with_underscore'!A1",
    target: :sheet,
    ref: 'A1'
  )
end

workbook.add_worksheet(name: "basic_name_with_underscore") do |sheet|
  sheet.add_row ["BasicName"]
  sheet.add_hyperlink(
    location: "'BasicName'!A1",
    target: :sheet,
    ref: 'A1'
  )
end

package.serialize(output)
```

Note how one can click the link in the second worksheet(linking to "BasicName") and it correct links to the first, but the link in the first worksheet(linking to "basic_name_with_underscore") is broken as the hyperlinker is converting the link to the worksheet "BasicNameWithUnderscore" which doesn't exist.

**Comment by realtradam** [comment] 2023-11-10 17:38
I tested this on Linux and on Windows. Same problem on both platforms.

**Comment by straydogstudio** [comment] 2023-11-15 17:22
Thanks @realtradam. Do you have any interest in creating a pull request?

**Comment by tagliala** [comment] 2023-11-15 18:01
Hi, the problem is here:

https://github.com/caxlsx/caxlsx/blob/333331d54639685046d0aeb11a605a729edba656/lib/axlsx/workbook/worksheet/worksheet_hyperlink.rb#L63

It is missing the third parameter, `false`, to prevent camelization of attributes

However, I cannot estimate the side effects of this change

**Comment by gr8bit** [comment] 2023-11-17 22:59
Thanks for the research @tagliala, I added a PR. All existing tests were unaffected by the suggested change.

**Comment by straydogstudio** [comment] 2023-11-17 23:51
PR merged

**Closed** 2023-11-17 23:51 UTC
