### ISSUE TITLE
NameError: uninitialized constant Axlsx

### ISSUE THREAD

**Issue by marisveide** [caxlsx/caxlsx#9] opened 2019-10-01 06:58 UTC
Hello!

I might be overlooking something obvious, but I cannot make `Axlsx` work with the new `caxlsx` gem.

## Here's what I do to reproduce that:
1. I create a new Rails project.
2. I add `gem 'caxlsx'` to Gemfile
3. I run `bundler` - I see that the `caxlsx` dependency is being resolved.
4. I try to call `Axlsx::Package.new` and I get an error: `NameError: uninitialized constant Axlsx`.

Here is the clean GitHub repo which reproduces the issue by those steps:
https://github.com/marisveide/rails-caxlsx

There is a test case under `./test/system/caxlsx_test.rb`.

Thank you so much for your help!

Maris

**Comment by straydogstudio** [comment] 2019-10-01 13:17
Thanks @marisveide. An unexpected consequence of renaming the gem, which we had to do. Will release a new version shortly.

**Comment by straydogstudio** [comment] 2019-10-04 17:58
3.0.1 released with this fix.

**Closed** 2019-10-04 18:03 UTC

**Comment by marisveide** [comment] 2019-10-04 20:33
@straydogstudio - yes, that new release works perfectly!
Thank you so much!

**Comment by straydogstudio** [comment] 2019-10-04 21:39
You’re welcome

**Comment by maland** [comment] 2020-01-17 08:07
not working for me, still had to require axlsx in the model where i want to access Axlsx

**Comment by noniq** [comment] 2020-01-17 10:33
@maland Can you provide a minimal self-contained example (like the original poster did in https://github.com/caxlsx/caxlsx/issues/9#issue-500703679) for reproducing the problem?

**Comment by maland** [comment] 2020-01-18 11:44
short disclaimer: i only listed caxlsx_rails gem in my Gemfile and not caxlsx gem, so probably the requiring issues is on caxlsx_rails gem side.

How to reproduce:

1. I create a new Rails project.
2. I add gem 'caxlsx_rails' to Gemfile
3. I run bundler - I see that the caxlsx dependency is being resolved.
4. In console i try to call Axlsx::Package.new and I get an error: NameError: uninitialized constant Axlsx.

but upon listing `gem 'caxlsx_rails' ` directly in the Gemfile i can call Axlsx::Package.new

**Comment by noniq** [comment] 2020-01-18 14:28
You're right. However, when using `axlsx_rails` instead of `caxlsx_rails` the behaviour is identical. Not sure, but this might be intended behaviour. If you think this is a bug, please open an issue in the [caxlsx_rails](https://github.com/caxlsx/caxlsx_rails) project. Thanks!

**Comment by straydogstudio** [comment] 2020-01-19 03:20
@maland I tested this in Rails 6 and I find your results. I also can't get Caxlsx to auto load using axlsx_rails. A google search has some suggestions that are several years old that don't work. I'm open to it, but the easiest solution is to simply put caxlsx in your Gemfile.
