### ISSUE TITLE
Images don't work

### ISSUE THREAD

**Issue by palmaste** [caxlsx/caxlsx#51] opened 2020-05-12 09:10 UTC
I'm using Ruby 2.6.6-1-x64 on Windows and caxlsx 3.0.1.
The images do not appear on the worksheet.
It seems that the images are only partially copied in subfolder xl/media of xlsx file.
If I simply swap to the axlsx library, everything works again.

Example:

```
#require 'axlsx'
require 'caxlsx'

p = Axlsx::Package.new

p.workbook.add_worksheet(:name => "Basic Worksheet") do |sheet|
  
  sheet.add_row ["First Column", "Second", "Third"]
  sheet.add_row [1, 2, 3]
  
  img = 'image1.jpeg'
  sheet.add_image(:image_src => img, :noSelect => true, :noMove => true, :hyperlink=>"https://github.com/caxlsx/caxlsx") do |image|
    image.width=720
    image.height=666
    image.hyperlink.tooltip = "Labeled Link"
    image.start_at 1, 5
  end
  
end

p.use_shared_strings = true
p.serialize('simple.xlsx')
```

[simple.xlsx](https://github.com/caxlsx/caxlsx/files/4614447/simple.xlsx)

**Comment by noniq** [comment] 2020-05-13 08:49
Thanks for the report! I’m not using Windows so it’s hard for me to investigate this further.

Which version of axlsx are you using?

**Comment by palmaste** [comment] 2020-05-13 08:56
axlsx-2.0.1

**Comment by straydogstudio** [comment] 2020-05-13 14:40
Just ran it on my Windows machine and can confirm. 

@palmaste Did you use a ruby windows installer, or another method, to install ruby?

**Comment by straydogstudio** [comment] 2020-05-13 14:44
Note: Switching from axlsx to caxlsx changes from rubyzip-1.0.0 to rubyzip-2.3.0.

**Comment by palmaste** [comment] 2020-05-13 14:45
@straydogstudio  Yes, I used rubyinstaller-devkit-2.6.6-1-x64.exe

**Comment by straydogstudio** [comment] 2020-05-19 16:32
@palmaste @noniq Note I have been able to reproduce this, and spend some time on it. I've not been able to isolate the problem yet. It took me a while to get debugging working on my Windows machine.

**Comment by noniq** [comment] 2020-05-19 17:04
Just a wild guess: Could it be that we are reading / writing the image file somewhere without the “binary” flag? IIRC this doesn’t hurt on Unix-based systems, but may lead to corrupt files on Windows.

**Comment by palmaste** [comment] 2020-05-19 18:09
@straydogstudio Thank you. Currently I continue to use axlsx, but the problem is the dependency on the old version of rubyzip which prevents updating other gems.

**Comment by noniq** [comment] 2020-05-19 18:21
@palmaste There's a version 2.0.2 of caxlsx which is still based on the v2-branch of axlsx, but contains an updated Rubyzip dependency: https://rubygems.org/gems/caxlsx/versions/2.0.2 

Maybe you could use this as a workaroud before upgrading to caxlsx 3.

**Comment by palmaste** [comment] 2020-05-20 11:48
@noniq Thank you. It works! It seems to depend on rubyzip-1.3.0. Anyway it'is a step forward.

**Comment by dicamarques14** [comment] 2020-07-16 10:57
Has this issue been fixed? I recently found this problem on my work Windows pc. But tried the script in a Ubuntu server and it worked

**Comment by straydogstudio** [comment] 2020-07-16 14:48
@dicamarques14 @noniq @palmaste I have isolated the problem to an IO call. I've tried to reproduce the issue outside of Rails but haven't completed that part. I will try to get to it soon.

Here is the location it occurs in caxlsx: https://github.com/caxlsx/caxlsx/blob/master/lib/axlsx/package.rb#L165-L168

**Comment by noniq** [comment] 2020-07-16 15:08
Maybe changing line 167 like this fixes the problem?

```ruby
zip.write IO.read(part[:path], mode: "rb")
```

**Comment by straydogstudio** [comment] 2020-07-16 15:14
Looks like that did it. I think you mentioned that before Stefan. I'm sorry I missed it. I'll push out a new release. Do we have anything else that should be included?

**Comment by noniq** [comment] 2020-07-16 15:26
I think there have been two or three small fixes since the last release, but they are already merged and mentioned in the Changelog (section “Unreleased”). Nothing else on my radar, currently. Let's do a release! 🚀

**Comment by straydogstudio** [comment] 2020-07-16 15:27
Sounds good. Once testing passes I'll bump the version number and release.

**Comment by straydogstudio** [comment] 2020-07-16 18:10
3.0.2 released. @palmaste Please test as you have time.

**Closed by straydogstudio** 2020-07-16 18:10 UTC

**Comment by palmaste** [comment] 2020-07-20 08:12
@straydogstudio It works! Thank you all.
