### ISSUE TITLE
Memory leak from sheet.add_row on 3.3.0

### ISSUE THREAD

**Issue by neongrau** [caxlsx/caxlsx#179] opened 2023-01-20 11:43 UTC
I'm having a memory issue with about 90k-100k rows split over 18 sheets in a workbook.
Memory climbs to 800MB-1GB with the final serialize only making about 20MB of a difference.
If i just do the data fetching, formatting and adding styles but leave out `sheet.add_row` the process will only reach 220MB-300MB.

Manually calling GC.start does not really make more than a few MB of a difference.

Here's a simple example script to replicate:

```ruby
def run_test
  p = Axlsx::Package.new
  wb = p.workbook

  (1..10).to_a.each do |num|
    name = "Sheet #{num}"
    puts "adding #{name}"
    sheet = wb.add_worksheet(name: name)
    10000.times do
      sheet.add_row [ SecureRandom.alphanumeric(100), rand(2)==0, rand(10000)] * 10
    end
  end

  puts "RAM: %.1fMB used" % [`ps -o rss= -p #{$$}`.to_f/1024]
  puts "=" * 80
  puts "finished adding data, now serializing to example.xlsx..."
  puts "=" * 80
  p.serialize 'example.xlsx'


  puts "RAM: %.1fMB used" % [`ps -o rss= -p #{$$}`.to_f/1024]
  puts "=" * 80
  puts "finished serialize, now trying GC..."
  puts "=" * 80
  wb = nil
  p = nil
  GC.start

  puts "RAM: %.1fMB used" % [`ps -o rss= -p #{$$}`.to_f/1024]
  puts "=" * 80
  puts "press enter for another run, ctrl+c to quit"
  puts "=" * 80
  $stdin.gets("\n")
  nil
end

10.times do
  run_test
end
```

**Comment by constantins2001** [comment] 2023-01-20 13:25
also seeing this issue, causes problems on production ^^

**Comment by neongrau** [comment] 2023-01-20 14:32
Might want to add this shows most noticable on macos (arm64).
The final Excel file is around 15MB and contains less than 120MB of XML data.
Most astounding that to generate the file about 700-800MB of RAM are consumed.

**Comment by kiskoza** [comment] 2023-01-23 14:33
I can see the increasing memory when I'm running the script above, but I wasn't able to reproduce it when I've added a memory profiler to find where's the leak, so I'm not sure if it's really a leak and not just a bloat that goes up and up before reaching a plateau - I'm trying to reach the plateau or prove that it's really a leak.

It's also worth a shot to figure out if we can reduce the required memory, but I can't promise anything there.

Could you help me out with your Ruby versions? Are you using YIT or jemalloc? Might be easier to debug if we're on the same setup.

**Comment by neongrau** [comment] 2023-01-23 14:45
On ruby 3.1 with jemalloc and `ENV MALLOC_CONF narenas:2,background_thread:true,abort_conf:true` on production. 

While on my local dev machine (macOS) the bloat piles up fast and rarely gets garbage collected on Linux it seems to be garbage collected fairly quick. Just that to create that 15MB xlsx our sidekiq hits max memory and is being killed before it can finish.

**Comment by azrazalea-debtbook** [comment] 2023-04-11 16:40
We're also seeing similar, using jemalloc and memory arenas set to 2.

We use the gem heavily with lots of exports via sidekiq jobs (multi threaded processes with 5 jobs/threads each) and have seen the memory climb to 4-5GB for the process.

This could be related to https://github.com/caxlsx/caxlsx/blob/c5ddbe7cd9bb15e8b247e6b5a5e359d02dd5b9fe/lib/axlsx/workbook/worksheet/cell.rb#L500 and similar behavior. A lot of those casts are going to cause a copy of the data to be created, and if this is happening a lot of times this could balloon memory. The GC can't garbage collect the values still in the sheets data structure after casting because the sheet still has references, and it can't collect the original values because the lexical scope is still open for those.

I don't think this by itself explains the entire problem, but similar pass-by-value over pass-by-reference issues could be contributing.

Any ideas on how we can address this? This might climb to the priority level for my company where I end up focused on this issue soon.

**Comment by azrazalea-debtbook** [comment] 2023-04-11 16:46
I was looking for somewhere that the reference to the original pre-cast data wasn't released or that it was referenced globally but I'm not seeing anything yet

**Comment by pkmiec** [comment] 2023-04-27 16:21
I have become best friends with `ruby-prof` and `memory_profiler` over the past few days trying to optimize our xlsx generation. I'm not sure whether I see a memory leak, but I definitely see memory bloat. Here are some areas for improvement,
- Currently, the ZipCommand uses `@buffer`, a StringIO, to cache the output for each entry in memory before writing it to disk in `#write_file`. It seems possible to just write directly to file like so, 
  ```ruby
  class ZipCommand
    def put_next_entry(entry)
      write_file
      @current_file = "#{@dir}/#{entry.name}"
      @files << entry.name
      FileUtils.mkdir_p(File.dirname(@current_file))
      @buffer = File.open(@current_file, "wb")
    end

    private

    def write_file
      @buffer.close if @current_file
      @current_file = nil
      @buffer = nil
    end
  end
  ``` 
  I am not familiar with all the use-cases, so I am not sure whether there is a reason to hold the buffer in memory? Is it related to `to_stream` perhaps?
- The validators are sprinkled all over the code and eat up CPU / memory. I suppose it is nice to validate sometimes, but, at least in my case, I know all these values / types are correct. For example,
  ```ruby
  def self.validate_boolean(v)
    DataTypeValidator.validate(:boolean, [String, Integer, Symbol, TrueClass, FalseClass], v, lambda { |arg| [0, 1, "true", "false", :true, :false, true, false, "0", "1"].include?(arg) })
  end
  ```
  creates the two arrays and the lambda and the closure each time. I already see a couple of places where the validation is commented out with the reason being performance (https://github.com/caxlsx/caxlsx/blob/master/lib/axlsx/workbook/worksheet/col.rb#L114).
- The `Axlsx#camel` is called over and over again to convert the same snake cased serialized attributes (i.e. `outline_level`, `custom_height`). Other serialized attributes are already camel cases (i.e. `aboveAverage`, `noChangeAspect`), but `#camel` uses `gsub` which will allocate memory regardless of whether there is anything to change. It would be better to require all the serialized attributes to be camel cases and avoid the call to `#camel` all together, however, that would be a breaking change. The `#camel` is also used for the boolean values which could also be avoided.
- The `#declared_attributes` uses `Axlsx#instance_values_for` which allocates memory for all instances variables to then exclude the one with nil values and ones that are not xml_attributes.

I am happy to make some of these improvements, but since I am only using a small set of features for the very specific purpose, I would need guidance in terms of what is desired / acceptable. 

Cheers!

**Comment by tagliala** [comment] 2023-08-02 10:23
keep open

**Comment by tagliala** [comment] 2023-08-02 11:10
Situation on current master (Apple Silicon, x86 Ruby):

```
adding Sheet 1
adding Sheet 2
adding Sheet 3
adding Sheet 4
adding Sheet 5
adding Sheet 6
adding Sheet 7
adding Sheet 8
adding Sheet 9
adding Sheet 10
RAM: 208.8MB used
================================================================================
finished adding data, now serializing to example.xlsx...
================================================================================
RAM: 218.6MB used
================================================================================
finished serialize, now trying GC...
================================================================================
RAM: 160.6MB used
================================================================================
```

**Comment by tagliala** [comment] 2023-10-19 07:32
Hi @azrazalea-debtbook , sorry but I'm not a maintainer

There is one major PR to merge before the release of a 4.0.0 version: #189, and hopefully #197 

However, if your application has a staging environment, giving `master` a try would be good to detect potential issues in advance

**Comment by tagliala** [comment] 2023-10-31 08:55
Please check against 4.0. Trade-offs have been made on retained memory but the overall situation should be improved

**Comment by kiskoza** [comment] 2024-01-12 14:09
I think we're in a lot better place than we were before, I'm closing this ticket. Feel free to open a new one, in case anyone sees any regression or has new ideas to improve the code further

**Closed by kiskoza** 2024-01-12 14:09 UTC

**Comment by sebfie** [comment] 2024-03-25 08:02
Hello, i am using last version of the gem (4.1.0) with ruby 3.3 and jmalloc and I do not have the result you showed @tagliala  : 

adding Sheet 1
adding Sheet 2
adding Sheet 3
adding Sheet 4
adding Sheet 5
adding Sheet 6
adding Sheet 7
adding Sheet 8
adding Sheet 9
adding Sheet 10
RAM: 310.2MB used
================================================================================
finished adding data, now serializing to example.xlsx...
================================================================================
RAM: 317.9MB used
================================================================================
finished serialize, now trying GC...
================================================================================
RAM: 263.6MB used
================================================================================
press enter for another run, ctrl+c to quit
================================================================================

**Comment by tagliala** [comment] 2024-03-25 09:52
Hi, v4 is in a much better situation than v3.

Please note that Ruby 3.3.0 has an issue with memory #336
